---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
```{r}
library(ggplot2)
library(dplyr)
library(reshape2)
library(ggthemes)
source("R:/home/Matching/Matching-Applied/Scripts/match_functions.R")

```

```{r}
res <- read.csv("R:/home/Matching/Matching-Applied/Results/res_df_simul2.csv")
res <- read.csv("R:/home/Matching/Matching-Applied/Results/matched/res_aggregate_exp1.csv")
res <- read.csv("R:/home/Matching/Matching-Applied/Results/res_mod1_j69.csv")
```

```{r}
res <- read.csv("R:/home/Matching/Matching-Applied/Results/matched/res_aggregate_exp1.csv")
res <- read.csv("R:/home/Matching/Matching-Applied/Results/matched/res_exp1_j204_summary.csv")
```

```{r}
map <- read.csv("R:/home/Matching/Matching-Applied/Results/res_exp1_map.csv")
colnames(map)[1] <- "map_idx"

file.list <- dir("R:/home/Matching/Matching-Applied/Results/matched/", pattern = "res_exp1.*summary.csv", full.names=T)
res <- do.call(bind_rows, lapply(file.list, read.csv))

file.list <- dir("R:/home/Matching/Matching-Applied/Results/unmatched/", pattern = "res_exp1.*summary.csv", full.names=T)
res_unmatched <- do.call(bind_rows, lapply(file.list, read.csv))
```

# Vary total N, impact on time
```{r}
p.dat <- res %>%
  distinct(n, method, distance, .keep_all = T) %>%
  mutate(n = factor(n))
ggplot(p.dat, aes(x=time.sec_mean, y = method, colour=distance)) +
  geom_point(size = 1, position = position_dodge(width=0.5)) +
  geom_linerange(aes(xmin=time.sec_mean-time.sec_sd, xmax=time.sec_mean+time.sec_sd), position = position_dodge(width=0.5)) +
  facet_wrap(~n, nrow = 1)
ggplot(p.dat, aes(x=ESS.total.perc_mean, y = adjusted_confint.coverage_mean, group=n, colour=n)) +
  geom_point(size = 1, position = position_dodge(width=0.5))+
  facet_wrap(~method, nrow = 1)
ggplot(p.dat, aes(x=adjusted_confint.coverage_mean, y = method, colour=distance)) +
  geom_point(size = 1, position = position_dodge(width=0.5))+
  facet_wrap(~n, nrow = 1)
```
# Vary pk
```{r}
p.dat <- res %>%
  distinct(pk, method, distance, .keep_all = T) %>%
  mutate(pk = factor(pk))
ggplot(p.dat, aes(x=time.sec_mean, y = method, colour=distance)) +
  geom_point(size = 1, position = position_dodge(width=0.5)) +
  geom_linerange(aes(xmin=time.sec_mean-time.sec_sd, xmax=time.sec_mean+time.sec_sd), position = position_dodge(width=0.5)) +
  facet_wrap(~pk, nrow = 1)
ggplot(p.dat, aes(x=ESS.total.perc_mean, y = method, colour=distance)) +
  geom_point(size = 1, position = position_dodge(width=0.5))+
  facet_wrap(~pk, nrow = 1)
ggplot(p.dat, aes(x=adjusted_confint.coverage_mean, y = method, colour=distance)) +
  geom_point(size = 1, position = position_dodge(width=0.5))+
  facet_wrap(~pk, nrow = 1)
```
# Vary nu_xy
```{r}
p.dat <- res %>%
  distinct(nu_xy, method, distance, .keep_all = T) %>%
  mutate(nu_xy = factor(nu_xy))
ggplot(p.dat, aes(x=time.sec_mean, y = method, colour=distance)) +
  geom_point(size = 1, position = position_dodge(width=0.5)) +
  geom_linerange(aes(xmin=time.sec_mean-time.sec_sd, xmax=time.sec_mean+time.sec_sd), position = position_dodge(width=0.5)) +
  facet_wrap(~nu_xy, nrow = 1)
ggplot(p.dat, aes(x=ESS.total.perc_mean, y = method, colour=distance)) +
  geom_point(size = 1, position = position_dodge(width=0.5))+
  facet_wrap(~nu_xy, nrow = 1)
ggplot(p.dat, aes(x=adjusted_confint.coverage_mean, y = method, colour=distance)) +
  geom_point(size = 1, position = position_dodge(width=0.5))+
  facet_wrap(~nu_xy, nrow = 1)
```

```{r}
c("ESS.total.perc", "SMD",  "Var.ratio", "KS", "SMD.PBR", "time.sec", "unadjusted_estimate", "unadjusted_std.error", "unadjusted_squared.error", "unadjusted_mse", "unadjusted_confint.upper")
# need to compare with method null!
# at some point may need to plot the full thing
# for pk > 1, need to look at SMD.mean_mean, max, etc

```





######################
######################


```{r}
p.dat <- res %>%
  filter(n==1000, stat.formula== stat.formula[1]) %>%
  mutate(Total_n = All..ESS..Control + All..ESS..Treated,
         Total_matched = Matched..ESS..Control + Matched..ESS..Treated,
         ESS_control_remainder = All..ESS..Control - Matched..ESS..Control,
         ESS_treated_remainder = All..ESS..Treated - Matched..ESS..Treated) %>%
  select(map_idx, Total_matched, "Matched..ESS..Control", "Matched..ESS..Treated") %>%
  group_by(map_idx) %>%
  summarise_if(is.numeric,list(mean = ~mean(.), sd = ~sd(.), se = ~sd(./sqrt(.)))) %>%
  left_join(res[,1:11], by = "map_idx", multiple = "first")

p.dat %>% ggplot(p.dat, aes(x=Total_matched_mean, y=distance)) +
  geom_point() +
  facet_wrap(~ method + estimand + treat_p)
```


```{r}
%>%
  mutate(Total_n = All..ESS..Control + All..ESS..Treated,
         Total_matched = Matched..ESS..Control + Matched..ESS..Treated,
         ESS_control_remainder = All..ESS..Control - Matched..ESS..Control,
         ESS_treated_remainder = All..ESS..Treated - Matched..ESS..Treated) %>%
  select("method", "distance", Total_n, Total_matched, ESS_control_remainder, "Matched..ESS..Control", ESS_treated_remainder, "Matched..ESS..Treated") %>%
  melt(measure.vars = c("ESS_control_remainder", "Matched..ESS..Control", "ESS_treated_remainder", "Matched..ESS..Treated")) %>%
  mutate(value = value/Total_n)

ggplot(p.dat, aes(x=value, y=distance, fill=variable)) +
  geom_bar(stat="identity") +
  facet_wrap(~ method, nrow =1) +
  scale_fill_tableau() +
  theme_few() +
  theme(legend.key.size = unit(1, 'mm'),
        legend.key.height = unit(1, 'mm'),
        legend.key.width = unit(1, 'mm'),
        legend.title = element_text(size=10),
        legend.text = element_text(size=8))

```

```{r}
p.dat <- res %>%
  filter(stat.formula== stat.formula[1]) %>%
  select("method", "distance", time)

ggplot(p.dat, aes(x=time, y=distance, group =1, colour =time)) +
  geom_point(size = 1.5, shape=18) +
  geom_line(orientation = "y") +
  facet_wrap(~ method, nrow = 1) +
  scale_colour_gradient_tableau() +
  theme_few() +
  theme(legend.key.size = unit(1, 'mm'),
      legend.key.height = unit(10, 'mm'),
      legend.key.width = unit(1, 'mm'),
      legend.title = element_text(size=10),
      legend.text = element_text(size=8))
```
```{r}
p.dat <- res %>%
  filter(stat.formula== stat.formula[1]) %>%
  select(method, distance, ends_with("Mean.Diff.")) %>%
  melt()

ggplot(p.dat, aes(x=value, y=distance, group =variable, colour= variable)) +
  geom_vline(xintercept = 0.1, linetype = "dotted", colour ="grey") +
  geom_point(size = 1.5, shape=18) +
  geom_line(orientation = "y") +
  facet_wrap(~ method, nrow = 1) +
  scale_colour_tableau() +
  theme_few() +
  theme(legend.key.size = unit(1, 'mm'),
        legend.key.height = unit(1, 'mm'),
        legend.key.width = unit(1, 'mm'),
        legend.title = element_text(size=10),
        legend.text = element_text(size=8))
```
```{r}
p.dat <- data.frame()
stat.ids = c("unadjusted", "adjusted", "mixed", "marginal")
for (stat.id in stat.ids) {
  p.dat.tmp <- res %>%
  filter(stat.formula== unique(stat.formula)[1]) %>%
  select(method, distance, stat.formula, starts_with(stat.id))
colnames(p.dat.tmp) <- gsub(paste0(stat.id, "_"), "", colnames(p.dat.tmp))
p.dat.tmp$variable <- stat.id
p.dat <- rbind(p.dat, p.dat.tmp)
}
p.dat$pval <- -log10(p.dat$pval)

ggplot(p.dat, aes(x=estimate, y=distance, group =variable, colour= variable)) +
  geom_vline(xintercept = 1, linetype = "dotted", colour="grey") +
  geom_point(size = 1.5, position = position_dodge(width=0.5), shape=18) +
  geom_linerange(aes(xmin=confint.lower, xmax=confint.upper), position = position_dodge(width=0.5)) +
  facet_wrap(~ method, nrow = 1)+
  scale_colour_tableau() +
  theme_few() +
  theme(legend.key.size = unit(2, 'mm'),
        legend.key.height = unit(2, 'mm'),
        legend.key.width = unit(2, 'mm'),
        legend.title = element_text(size=10),
        legend.text = element_text(size=8))
```
```{r}
ggplot(p.dat, aes(x=pval, y=distance, group =variable, colour= variable)) +
  geom_point(size = 1.5, position = position_dodge(width=0.5), shape=18) +
  facet_wrap(~ method, nrow = 1) +
  scale_colour_tableau() +
  theme_few() +
  theme(legend.key.size = unit(2, 'mm'),
        legend.key.height = unit(2, 'mm'),
        legend.key.width = unit(2, 'mm'),
        legend.title = element_text(size=10),
        legend.text = element_text(size=8))
```
```{r}
p.dat <- data.frame()
stat.ids = c("unadjusted", "adjusted", "mixed", "marginal")
for (stat.id in stat.ids) {
  p.dat.tmp <- res %>%
  filter(stat.formula== unique(stat.formula)[2]) %>%
  select(method, distance, stat.formula, starts_with(stat.id))
colnames(p.dat.tmp) <- gsub(paste0(stat.id, "_"), "", colnames(p.dat.tmp))
p.dat.tmp$variable <- stat.id
p.dat <- rbind(p.dat, p.dat.tmp)
}
p.dat$pval <- -log10(p.dat$pval)

ggplot(p.dat, aes(x=estimate, y=distance, group =variable, colour= variable)) +
  geom_vline(xintercept = 1, linetype = "dotted", colour="grey") +
  geom_point(size = 1.5, position = position_dodge(width=0.5), shape=18) +
  geom_linerange(aes(xmin=confint.lower, xmax=confint.upper), position = position_dodge(width=0.5)) +
  facet_wrap(~ method, nrow = 1) +
  scale_colour_tableau() +
  theme_few() +
  theme(legend.key.size = unit(2, 'mm'),
        legend.key.height = unit(2, 'mm'),
        legend.key.width = unit(2, 'mm'),
        legend.title = element_text(size=10),
        legend.text = element_text(size=8))
```

```{r}
ggplot(p.dat, aes(x=pval, y=distance, group =variable, colour= variable)) +
  geom_vline(xintercept = -log10(0.05), linetype = "dotted", colour="grey") +
  geom_point(size = 1.5, position = position_dodge(width=0.5), shape=18) +
  facet_wrap(~ method, nrow = 1)  +
  scale_colour_tableau() +
  theme_few() +
  theme(legend.key.size = unit(2, 'mm'),
        legend.key.height = unit(2, 'mm'),
        legend.key.width = unit(2, 'mm'),
        legend.title = element_text(size=10),
        legend.text = element_text(size=8))
```